### ISSUE TITLE
Bug: The argument must be a React element, but you passed null with & weird behavior in corners - newest version

### ISSUE THREAD

**Issue by alexco2** [SrBrahma/react-native-shadow-2#56] opened 2022-08-14 07:42 UTC
Hey @SrBrahma, thank you for the update! I (perhaps) notices a bug though.

When I upgraded to the new Version I get the following error. Am I doing something wrong?

`The argument must be a React element, but you passed null.`

Here I have a small code example

```
import * as React from 'react';
import { Text, View, StyleSheet } from 'react-native';
import {Shadow} from "react-native-shadow-2"

export default function App() {
  return (
    <Shadow
      distance={15}
      style={{width:50, height:50}}
      startColor={'#eb9066d8'}
      endColor={'#ff00ff10'}
      offset={[3, 4]}>
      <View
        style={{
          borderTopStartRadius: 24,
          borderBottomEndRadius: 0,
          borderRadius: 10,
          backgroundColor: '#c454f0dd',
        }}>
        <Text style={{ margin: 20, fontSize: 20 }}>🤯</Text>
      </View>
    </Shadow>
  );
}

```
You can find a snack of the bug here:
https://snack.expo.dev/@expoco2/bug-in-react-native-shadow-2

If I delete `width` and `height` in style, I get the following error btw:
`undefined is not an object (evaluating 'd.width')`
Can you say something about that as well?

I am using the latest react-native version

**Comment by SrBrahma** [comment] 2022-08-14 09:50
Many thanks for the report. I will fix this asap.

**Comment by SrBrahma** [comment] 2022-08-14 13:30
@alexco2, I have fixed the `undefined is not an object (evaluating 'd.width')` in the just published 7.0.3 (may take a while to be available on Snack). Also, that error didn't happen on Snack here. The error was caused by `StyleSheet.flatten(false)` returning undefined, contrary to its type definition. Maybe the RN version that Expo 46 the Snack uses has this fixed.

I couldn't get the `The argument must be a React element, but you passed null.` error. After the above fix, the code you gave run well on RN web. Please, if you still have it after trying the 7.0.3, ensure that everything is alright in your test case and try to give me any further info that can help me to reproduce this issue.

And again, many thanks for the report!

**Comment by alexco2** [comment] 2022-08-14 13:36
@SrBrahma thank you for your quick report!

Have you tried running the expo snack on a android emulator? I get the following error with expo go on a Samsung s21

![Screenshot_20220814-153504_Expo Go.jpg](https://user-images.githubusercontent.com/61253912/184539598-14199ab1-4d6f-4172-a58f-f351642d8f18.jpg)

**Comment by SrBrahma** [comment] 2022-08-14 13:39
Yup, having the same issue on Android, thanks for pointing it out. I will fix it asap.

**Comment by SrBrahma** [comment] 2022-08-14 14:28
@alexco2 Many many thanks for both reports. Just published 7.0.4 with this fix.

This error was due to react-native-svg not allowing

`{!paintInside && <Stop offset={radius / shadowRadius} stopOpacity={0}/>}`

inside the `RadialGradient` component. I've change it to

`{!paintInside ? <Stop offset={radius / shadowRadius} stopOpacity={0}/> : <></>}`

and it's now working.

Please do report any further issues!

(and also, beware that running your example may not show the shadow as width: 50, height: 50 may be smaller than the child, being beneath it)

**Comment by alexco2** [comment] 2022-08-14 14:30
Hello @SrBrahma thank you for your excellent support. Maybe you should open a way to sponsor a coffee ;)

**Comment by SrBrahma** [comment] 2022-08-14 14:33
Indeed! I have though about it on the past a few times. Maybe the time has come! Hehe.

Have a great Sunday!

**Comment by SrBrahma** [comment] 2022-08-14 15:06
Just added my humble Buy me a Coffee badge to the Readme ☕😋

Thanks for your contribution!

**Comment by alexco2** [comment] 2022-08-14 19:32
I think that is a good idea :)
I can confirm now that the bug does not appear in my case. One thing I noticed is a new and weird behavior in the corners of the shadow. I updated the snack as well. Here are screenshots of what i mean. Do you see it? If you want to I can open a new issue as well.

https://snack.expo.dev/@expoco2/weird-corners-in-react-native-shadow-2

<img width="196" alt="Bildschirmfoto 2022-08-14 um 21 29 55" src="https://user-images.githubusercontent.com/61253912/184551965-c511e9c8-e452-44d7-8b68-507b0e6e4bb7.png">
<img width="100" alt="Bildschirmfoto 2022-08-14 um 21 30 04" src="https://user-images.githubusercontent.com/61253912/184551968-9041b8a0-cb88-4317-a784-b9c917b2f738.png">

**Comment by alexco2** [comment] 2022-08-15 09:19
@SrBrahma I've checked again and I am also seeing the same behaviour in one of your examples on both iOS and android. You can see it in the previously mentioned snack

![Bildschirmfoto 2022-08-15 um 11 18 23](https://user-images.githubusercontent.com/61253912/184609724-d04ba8a6-ac5d-47b3-99fe-817ccabc1729.png)

<img width="332" alt="Bildschirmfoto 2022-08-15 um 11 17 45" src="https://user-images.githubusercontent.com/61253912/184609620-04e83388-58c0-431e-bb93-10efeb6d5ed1.png">

**Comment by SrBrahma** [comment] 2022-08-15 10:12
Hmmm. Strange. Will again fix it asap. Thanks for the report.

**Comment by SrBrahma** [comment] 2022-08-15 14:16
Hi, sorry for the trouble you had those days.

Once again, many thanks for your reports (and for the coffee you gave me! I will make a good use of it today when I take a walk here in the city 😄).

It's fixed on 7.0.5! Tested on Web, Android and iOS. It may take some good minutes to be available on Snack.

![image](https://user-images.githubusercontent.com/28177550/184632873-646d1878-3171-4d99-9e93-a2a710d06ab7.png)
*(beware that `textAlignVertical: 'center'` is an [Android-only style](https://reactnative.dev/docs/text-style-props#textalignvertical-android).)*

Cool nested shadow! I never tried having it before. I though it wouldn't work as the upper shadow would use the inner shadow size (using its distance), being around it and not around the children. I have an old idea of having an array of shadows, for a better performance and DX.

Please, do report any other found bugs.

**Closed by SrBrahma** 2022-08-15 14:16 UTC

**Comment by alexco2** [comment] 2022-08-15 14:59
Yes, don't worry about the trouble. This is an open-source project and there is no need for you to meet any requirements and especially not to apologise if something does not work. I really appreciate that you're doing that though! I hope you enjoy the coffee :D
Thanks for your fix. Your library is basically the only possibility to have neumorphism on android. This is why I am using it quite a lot in my project :)
Out of interest. Have you thought about moving from react-native-svg to react-native-skia? I don't know if it has any performance improvements, but it is currently heavily in development. Although the same could be said about react-native svg, since are working on fabric support :)

**Comment by SrBrahma** [comment] 2022-08-15 15:47
Yes, I have this old plan of moving to skia.

They have their Shadow component but it's very property-limited. I could use their gradients as I use the SVG ones.

But, strangely the [skia package](https://www.npmjs.com/package/@shopify/react-native-skia) weights 250MB. I don't know how much it adds to the final app size and I stopped my research when I found about this fact.

**Comment by alexco2** [comment] 2022-08-15 16:27
I think that is because of the whole skia dependency. I've seen multiple apps that use rn-skia that are not particulary big.

That one for example had less than 10mb
https://play.google.com/store/apps/details?id=finance.pinkpanda.mobile

Reference:
https://twitter.com/margelo_io/status/1520083516201000961?t=yCC3GUSMcemZ8LwnfDK8xQ&s=19

**Comment by nguyenhoanglam** [comment] 2022-09-22 05:09
@SrBrahma I still have this issue. v7.0.5 does not work!
