### ISSUE TITLE
Enabling RTL on Android causes distruption in shadows

### ISSUE THREAD

**Issue by abdullahkn287** [SrBrahma/react-native-shadow-2#26] opened 2021-09-23 08:15 UTC
On Android (Haven't had the chance to test on iOS), the shadows get extremely distrupted upon enabling Right-to-Left layout by using React's `I18nManager.forceRTL(true)` 

With RTL disabled, the shadows work perfectly: 
![image](https://user-images.githubusercontent.com/72031890/134474227-3d0fa7d8-6f27-4e44-9687-169de51665d7.png)

However as soon as I enable RTL, this is what I get:
![image](https://user-images.githubusercontent.com/72031890/134474381-7d2cf38e-cdd9-49b9-a86c-29b0e7e5c353.png)

For anyone looking for a temporary fix, you can use the `elevation` property whenever RTL is enabled by checking the `I18nManager.isRTL` property

**Comment by SrBrahma** [comment] 2021-09-23 15:32
I have no knowledge and experience with this. Do you know why this could be happening and how this could be fixed?

**Comment by serzh-f** [comment] 2021-09-24 07:59
+1. I have the same problem. When use RTL direction. 

Hm, I think we should find a solution

**Comment by SrBrahma** [comment] 2021-09-26 04:32
Can you create a minimum reproduction in Expo Snack?

https://snack.expo.dev/

**Comment by serzh-f** [comment] 2021-09-26 10:33
> Can you create a minimum reproduction in Expo Snack?

Hi! Here you can reproduce: https://snack.expo.dev/@7alcon/shadow

**Comment by SrBrahma** [comment] 2021-09-27 02:39
@serzh-f if you pass the prop `sides={['left']}`, you will see that the left shadow is showing up in the right, with a right to left shadow, as a left shadow does.

Looks like that this RTL inverts the horizontal reference somehow. In this shadow lib code we have

https://github.com/SrBrahma/react-native-shadow-2/blob/304aae17c651960a2a5725b38f997072465554e9/src/index.tsx#L316

to position the `left` shadow. Maybe it just switches left <-> right, I don't know.

Depending on how it works (and I ask you if you can find out what it exactly does), we can just check if it's enabled and switch the left to right and right to left.

**Comment by serzh-f** [comment] 2021-09-27 07:52
Yes. RTL just invert left property to right.
You can test it https://snack.expo.dev/@7alcon/shadow. I've added example with absolute text and right align. (but with RTL text on left side)

For example, you can add condition and check **I18nManager.isRTL**, and instead of right property you have to use left.

change left ---to--> right and right  ---to--> left.

**Comment by serzh-f** [comment] 2021-09-27 08:06
@SrBrahma  Yep. It works. I've just changed **left** property to **right**.

http://joxi.ru/eAOBq6vi6Dd7P2.jpg

**Comment by SrBrahma** [comment] 2021-10-01 22:00
@abdullahkn287 can you make me a Snack of your problematic case that created the image you sent here? For @serzh-f case I will either invert the gradients or invert the SVG parts, but your case looks more problematic.

I have some hypothesis on why it's happening and how to fix it, but I need to test them so I don't publish a new version that won't fix your issue and I also don't lose time polishing a wrong solution.

**Comment by SrBrahma** [comment] 2021-10-02 18:55
My concern was this:

![image](https://user-images.githubusercontent.com/28177550/135728381-3d4dc6a3-d600-4805-80cd-cd442732beb9.png)

I managed to reproduce this on the Sandbox, found out that the topRight and bottomRight (with RTL = Left) were having an X offset, and then I got it fixed.

Tell me if it's working or not! Released 5.1.0 via 70f95a6725aa60d0a1f8160641baecdc4a66ffbd

**Closed by SrBrahma** 2021-10-02 18:55 UTC
